In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, VT = np.linalg.svd(A)

print("Original Matrix:\n", A)
print("U Matrix:\n", U)
print("Singular Values:\n", S)
print("V Transpose:\n", VT)

Original Matrix:
 [[1 2]
 [3 4]
 [5 6]]
U Matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular Values:
 [9.52551809 0.51430058]
V Transpose:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
X = iris.data
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

print("Explained Variance Ratio:", pca.explained_variance_ratio_)
print("PCA Components:\n", X_pca[:5])


Explained Variance Ratio: [0.92461872 0.05306648]
PCA Components:
 [[-2.68412563  0.31939725]
 [-2.71414169 -0.17700123]
 [-2.88899057 -0.14494943]
 [-2.74534286 -0.31829898]
 [-2.72871654  0.32675451]]


In [ ]:
from scipy.stats import ttest_ind
group1 = [20, 22, 21, 19, 24]
group2 = [30, 28, 27, 32, 31]
print("Group 1: ",group1)
print("Group 2: ",group2)
t_stat, p_value = ttest_ind(group1, group2)

print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Reject Null Hypothesis: Significant difference")
else:
    print("Fail to Reject Null: No significant difference")


Group 1:  [20, 22, 21, 19, 24]
Group 2:  [30, 28, 27, 32, 31]
T-statistic: -6.640783086353598
P-value: 0.00016235209820893468
Reject Null Hypothesis: Significant difference


In [ ]:
from scipy.stats import ttest_1samp

sample = [22, 23, 21, 20, 24, 25]
population_mean = 20

t_stat, p_value = ttest_1samp(sample, population_mean)
print("Samples : ",sample)
print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Reject H0: Sample mean ≠ Population mean")
else:
    print("Fail to Reject H0: Sample mean ≈ Population mean")


Samples :  [22, 23, 21, 20, 24, 25]
T-statistic: 3.273268353539886
P-value: 0.022118466722329432
Reject H0: Sample mean ≠ Population mean


In [ ]:
from scipy.stats import ttest_rel

before = [65, 70, 68, 72, 66]
after = [75, 78, 74, 80, 76]

t_stat, p_value = ttest_rel(before, after)
print("Before: ",before)
print("After: ",after)
print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Reject H0: Significant change after treatment")
else:
    print("Fail to Reject H0: No significant change")


Before:  [65, 70, 68, 72, 66]
After:  [75, 78, 74, 80, 76]
T-statistic: -11.224972160321826
P-value: 0.0003587352603774513
Reject H0: Significant change after treatment


In [ ]:
from scipy.stats import chi2_contingency

# Example: Gender vs Preference
data = [[30, 10],  # Male: Likes, Dislikes
        [20, 40]]  # Female: Likes, Dislikes

chi2, p, dof, expected = chi2_contingency(data)

print("Chi-square Statistic:", chi2)
print("P-value:", p)

if p < 0.05:
    print("Reject H0: Variables are dependent")
else:
    print("Fail to Reject H0: Variables are independent")


Chi-square Statistic: 15.041666666666666
P-value: 0.00010516355403363098
Reject H0: Variables are dependent


In [ ]:
from scipy.stats import f_oneway

group1 = [20, 21, 19, 22]
group2 = [30, 28, 31, 29]
group3 = [25, 24, 26, 23]

f_stat, p_value = f_oneway(group1, group2, group3)

print("F-statistic:", f_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Reject H0: At least one group mean is different")
else:
    print("Fail to Reject H0: All group means are similar")


F-statistic: 48.8
P-value: 1.4763314494112804e-05
Reject H0: At least one group mean is different


In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
y_true = [1, 0, 1, 1, 0, 1, 0, 0]
y_pred = [1, 0, 1, 0, 0, 1, 1, 0]
print("True Matrix: ",y_true)
print("Predicted Matrix: ", y_pred)
cm = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:\n", cm)


True Matrix:  [1, 0, 1, 1, 0, 1, 0, 0]
Predicted Matrix:  [1, 0, 1, 0, 0, 1, 1, 0]
Confusion Matrix:
 [[3 1]
 [1 3]]
